### ISSUE TITLE
Please render a fully usable css file with classes from the svg filenames

### ISSUE THREAD

**Issue by Chris2011** [kisenka/svg-sprite-loader#152]
**Do you want to request a feature, report a bug or ask a question?**
Feature

**What is the current behavior?**
It only generates a sprite.svg file.

**What is the expected behavior?**
It would be nice to have a sprite.css file too, where this code is inside: 

```css
.svg-asm {
    background: url("svg/sprite.css-a740267f.svg") 74.19354838709677% 44.44444444444444% no-repeat;
}

.svg-asm-dims {
    width: 32px;
    height: 32px;
}

.svg-bat {
    background: url("svg/sprite.css-a740267f.svg") 0 0 no-repeat;
}

.svg-bat-dims {
    width: 88px;
    height: 88px;
}

.svg-c {
    background: url("svg/sprite.css-a740267f.svg") 35.483870967741936% 14.814814814814815% no-repeat;
}

.svg-c-dims {
    width: 32px;
    height: 32px;
}

.svg-clojure {
    background: url("svg/sprite.css-a740267f.svg") 0 40.74074074074074% no-repeat;
}
```

This is the output from the svg-sprite npm package, which is very handy. Here are the options for this:

`svg-sprite --css --css-render-css --css-example` --css-example will create a html where you see all your svg files on a page which is cool too.

Regards

Chris
